---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  labels:
    app: blue
  namespace: default
spec:
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
        - name: blue
          image: jpetazzo/color
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: blue
  labels:
    app: blue
spec:
  selector:
    app: blue
  ports:
    - port: 80
      targetPort: 80
